[package]
authors = ["theduke <chris@theduke.at>"]
name = "crates_io_api"
version = "0.1.0"

[dependencies]
time = "0.1.37"
chrono = { version = "0.3.1", features = ["serde"] }
reqwest = "0.6.1"
serde = "1.0.4"
serde_derive = "1.0.4"
serde_json = "1.0.2"
url = "1.4.0"
error-chain = "0.10"
