[package]
authors = ["theduke <chris@theduke.at>"]
name = "crates_io_api"
description = "API client for crates.io"
license = "MIT/Apache-2.0"
homepage = "https://github.com/theduke/crates_io_api"
repository = "https://github.com/theduke/crates_io_api"
documentation = "https://docs.rs/crates_io_api"
readme = "README.md"
keywords = [ "crates", "api" ]
categories = [ "web-programming", "web-programming::http-client" ]

version = "0.1.0"

[dependencies]
time = "0.1.39"
chrono = { version = "0.4.0", features = ["serde"] }
reqwest = "0.8.4"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
url = "1.6.0"
error-chain = "0.11.0"
